export const tourPackages = [
  {
    id: "1",
    duration: "6 Days / 5 Nights",
    destination: "Nepal",
    package_name: "Nepal Eid Offer 2026",
    price_bdt: 65899,
    fair_included: true,
    image:
      "https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=80&w=2070&auto=format&fit=crop",
    category: "Popular",
    highlights: ["Everest Viewpoint", "Kathmandu Tour", "Pokhara Lake"],
    rating: 4.9,
  },
  {
    id: "2",
    duration: "4 Days / 3 Nights",
    destination: "Nepal",
    package_name: "Nepal Tour Package",
    price_bdt: 16500,
    fair_included: true,
    image:
      "https://images.unsplash.com/photo-1469521669194-babb45599def?q=80&w=2070&auto=format&fit=crop",
    category: "Family",
    highlights: ["Chitwan Safari", "Lakeside Pokhara", "Pashupatinath Temple"],
    rating: 4.7,
  },
  {
    id: "3",
    duration: "2 Days / 1 Night",
    destination: "Sri Lanka",
    package_name: "Sri Lanka Tour Package",
    price_bdt: 28000,
    fair_included: false,
    image:
      "https://images.unsplash.com/photo-1546708973-b339540b5162?q=80&w=2076&auto=format&fit=crop",
    category: "Popular",
    highlights: ["Sigiriya Rock", "Tea Plantations", "Galle Fort"],
    rating: 4.8,
  },
  {
    id: "4",
    duration: "3 Days / 2 Nights",
    destination: "Maldives",
    package_name: "Maldives Tour Package",
    price_bdt: 38000,
    fair_included: false,
    image:
      "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?q=80&w=1965&auto=format&fit=crop",
    category: "Combo",
    highlights: ["Overwater Bungalow", "Snorkeling", "Sunset Cruise"],
    rating: 5.0,
  },
  {
    id: "5",
    duration: "4 Days / 3 Nights",
    destination: "Malaysia",
    package_name: "Malaysia Tour Package",
    price_bdt: 14500,
    fair_included: false,
    image:
      "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?q=80&w=1965&auto=format&fit=crop",
    category: "Family",
    highlights: ["Petronas Towers", "Batu Caves", "Genting Highlands"],
    rating: 4.6,
  },
  {
    id: "6",
    duration: "5 Days / 4 Nights",
    destination: "Thailand & Singapore",
    package_name: "Thailand Singapore Tour Package",
    price_bdt: 19500,
    fair_included: false,
    image:
      "https://images.unsplash.com/photo-1490077476659-095159692ab5?q=80&w=2070&auto=format&fit=crop",
    category: "Combo",
    highlights: ["Pattaya Beach", "Gardens by the Bay", "Universal Studios"],
    rating: 4.8,
  },
  {
    id: "7",
    duration: "5 Days / 4 Nights",
    destination: "Maldives",
    package_name: "Maldives Honeymoon Package",
    price_bdt: 89500,
    fair_included: false,
    image:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=2073&auto=format&fit=crop",
    category: "Popular",
    highlights: ["Private Villa", "Spa Treatment", "Candlelit Dinner"],
    rating: 5.0,
  },
  {
    id: "8",
    duration: "3 Days / 2 Nights",
    destination: "Singapore & Malaysia",
    package_name: "Singapore and Malaysia Family Package",
    price_bdt: 50000,
    fair_included: true,
    image: "/images/singapore.png",
    category: "Family",
    highlights: ["Sentosa Island", "Legoland", "Night Safari"],
    rating: 4.7,
  },
  {
    id: "9",
    duration: "7 Days / 6 Nights",
    destination: "Turkey",
    package_name: "Turkey Golden Tour 2026",
    price_bdt: 79900,
    fair_included: true,
    image:
      "https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=2076&auto=format&fit=crop",
    category: "Popular",
    highlights: ["Hagia Sophia", "Cappadocia Balloon", "Bosphorus Cruise"],
    rating: 4.9,
  },
  {
    id: "10",
    duration: "5 Days / 4 Nights",
    destination: "Indonesia",
    package_name: "Bali Family Retreat",
    price_bdt: 42000,
    fair_included: false,
    image:
      "https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=2076&auto=format&fit=crop",
    category: "Family",
    highlights: ["Tanah Lot Temple", "Ubud Rice Terraces", "Kuta Beach"],
    rating: 4.8,
  },
  {
    id: "11",
    duration: "6 Days / 5 Nights",
    destination: "Europe",
    package_name: "Paris & Rome Combo",
    price_bdt: 185000,
    fair_included: true,
    image:
      "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?q=80&w=2020&auto=format&fit=crop",
    category: "Combo",
    highlights: ["Eiffel Tower", "Colosseum", "Vatican City"],
    rating: 4.9,
  },
  {
    id: "12",
    duration: "4 Days / 3 Nights",
    destination: "Thailand",
    package_name: "Bangkok & Phuket Family",
    price_bdt: 31500,
    fair_included: false,
    image:
      "https://images.unsplash.com/photo-1506665531195-3566af2b4dfa?q=80&w=2070&auto=format&fit=crop",
    category: "Family",
    highlights: ["Phi Phi Islands", "Grand Palace", "Floating Market"],
    rating: 4.6,
  },
  {
    id: "13",
    duration: "8 Days / 7 Nights",
    destination: "Japan",
    package_name: "Japan Cherry Blossom Tour",
    price_bdt: 125000,
    fair_included: true,
    image:
      "https://images.unsplash.com/photo-1528360983277-13d401cdc186?q=80&w=2070&auto=format&fit=crop",
    category: "Popular",
    highlights: ["Mount Fuji", "Kyoto Temples", "Tokyo Shibuya"],
    rating: 5.0,
  },
  {
    id: "14",
    duration: "4 Days / 3 Nights",
    destination: "Dubai",
    package_name: "Dubai Combo Getaway",
    price_bdt: 55000,
    fair_included: false,
    image:
      "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=1965&auto=format&fit=crop",
    category: "Combo",
    highlights: ["Burj Khalifa", "Desert Safari", "Dubai Mall"],
    rating: 4.7,
  },
];

export const dummyFlights = [
  {
    flightNumber: "BG-021",
    airlineName: "Biman Bangladesh Airlines",
    aircraftModel: "Boeing 787-9 Dreamliner",
    departureTime: "2026-06-15T10:00:00Z",
    arrivalTime: "2026-06-15T18:00:00Z",
    price: 342,
    features: ["Free Meals", "Extra Legroom", "USB Ports"],
  },
  {
    flightNumber: "EK-582",
    airlineName: "Emirates",
    aircraftModel: "Airbus A380",
    departureTime: "2026-06-16T14:00:00Z",
    arrivalTime: "2026-06-16T22:30:00Z",
    price: 589,
    features: ["In-flight Wi-Fi", "Entertainment System", "Business Class"],
  },
  {
    flightNumber: "QR-639",
    airlineName: "Qatar Airways",
    aircraftModel: "Airbus A350-1000",
    departureTime: "2026-06-17T08:00:00Z",
    arrivalTime: "2026-06-17T20:00:00Z",
    price: 420,
    features: ["Flat Bed Seats", "Gourmet Dining", "Quiet Cabin"],
  },
];
